# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tisbg484-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Ashkan works/PDS_HW4/P2/CRC/CRC.cache/wt} [current_project]
set_property parent.project_path {D:/Ashkan works/PDS_HW4/P2/CRC/CRC.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Ashkan works/PDS_HW4/P2/CRC/CRC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{D:/Ashkan works/PDS_HW4/P2/CRC/CRC.srcs/sources_1/new/CRC_16.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CRC_16 -part xc7a200tisbg484-1L


write_checkpoint -force -noxdef CRC_16.dcp

catch { report_utilization -file CRC_16_utilization_synth.rpt -pb CRC_16_utilization_synth.pb }
