# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tisbg484-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.cache/wt} [current_project]
set_property parent.project_path {D:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{d:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp}}]
add_files -quiet {{d:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp}}]
read_vhdl -library xil_defaultlib {{D:/Ashkan works/PDS_HW4/P4/matrix_inv/matrix_inv.srcs/sources_1/new/top_matrix.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top_matrix -part xc7a200tisbg484-1L


write_checkpoint -force -noxdef top_matrix.dcp

catch { report_utilization -file top_matrix_utilization_synth.rpt -pb top_matrix_utilization_synth.pb }
