######################################################################
##
## Filename: shift_RTL.udo
## Created on: Fri Mar 22 4:59:39 PM Iran Daylight Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
